In [1]:
#P1
import numpy as np

def validar(msje, inf, sup):
    numero = int(input('Ingrese valor '+msje))
    if inf!=sup:
        while numero<inf or numero>sup:
            numero = int(input('Error\nIngrese valor '+msje))
    else:
        while numero<inf:
            numero = int(input('Error\nIngrese valor '+msje))
    return numero

def producto_escalar(u,v):
    s = 0
    N = len(u)
    for i in range(N):
        s = s+u[i]*v[i]
    return s

#A = np.array([4.0, 9.0, 6.0, -1.0, 3.0, -2.0])
#A = np.array( input('valor: ').split(' '), dtype=float )
#B = np.array([-3.0, 4.0, -7.0, 1.0, 8.0, -3.0])

n = validar('n>2: ', 3,3)
i = 0
A = []
B = np.empty(n) #alternativa a zeros, ones
while i<n:
    a = float(input('A: '))
    b = float(input('B: '))
    A.append(a)
    B[i] = b
    i = i+1
A = np.array(A)
print(A,B)

#Solución usando métodos (funciones) no numpy
print( producto_escalar(A,B) )
#Alternativa usando numpy: 
#Multiplicación punto a punto al ser array (array*array). Luego al hacer sum se suman todos los elementos del arreglo resultante
print( (A*B).sum() ) 
#Alternativa usando numpy:
#Multiplicación punto a punto usando solamente dot
print( np.dot(A,B) )

Ingrese valor n>2: 6
A: 4
B: -3
A: 9
B: 4
A: 6
B: -7
A: -1
B: 1
A: 3
B: 8
A: -2
B: -3
[ 4.  9.  6. -1.  3. -2.] [-3.  4. -7.  1.  8. -3.]
11.0
11.0
11.0


In [2]:
#P2
import numpy as np

def validar(msje, inf, sup):
    numero = int(input('Ingrese valor '+msje))
    if inf!=sup:
        while numero<inf or numero>sup:
            numero = int(input('Error\nIngrese valor '+msje))
    else:
        while numero<inf:
            numero = int(input('Error\nIngrese valor '+msje))
    return numero

def matriz_simetrica(m):
    x,y = m.shape
    s = 0
    for i in range(x):
        for j in range(y):
            if m[i][j] == m[j][i]:
                s = s+1
    if s==(x*y):
        print('La matriz es simétrica')
    else:
        print('La matriz no es simétrica')

#A = np.array( [ [4,9,6], [9,0,-7], [6,-7,-1] ])

N = validar('100>N>=2: ', 2, 99)
A = np.empty((N,N))
i = 0
while i<N:
    j = 0
    while j<N:
        valor = float( input(f'Ingrese valor {i,j}: ') )
        A[i,j] = valor #equivalente a A[i][j] en notación de listas
        j = j+1
    i = i+1

print(A)

#Solución usando métodos (funciones) no numpy
matriz_simetrica(A)
#Alternativa usando numpy: 
#shape entrega las dimensiones del arreglo (en este caso, 2D)
x,y = A.shape
#.T entrega la traspuesta del arreglo
#Al hacer == se compara elemento a elemento y se asigna un True (1) o un False (0)
#Se compara la suma de este arreglo resultante con la cantidad de elementos
print( (A == A.T).sum()==(x*y) )

Ingrese valor 100>N>=2: 3
Ingrese valor (0, 0): 4
Ingrese valor (0, 1): 9
Ingrese valor (0, 2): 6
Ingrese valor (1, 0): 9
Ingrese valor (1, 1): 0
Ingrese valor (1, 2): -7
Ingrese valor (2, 0): 6
Ingrese valor (2, 1): -7
Ingrese valor (2, 2): -1
[[ 4.  9.  6.]
 [ 9.  0. -7.]
 [ 6. -7. -1.]]
La matriz es simétrica
True


In [3]:
#P3
import numpy as np

def validar(msje, inf, sup):
    numero = int(input('Ingrese valor '+msje))
    if inf!=sup:
        while numero<inf or numero>sup:
            numero = int(input('Error\nIngrese valor '+msje))
    else:
        while numero<inf:
            numero = int(input('Error\nIngrese valor '+msje))
    return numero

def triangular_superior(m):
    x,y = m.shape
    flag = True
    for i in range(1, x):
        if flag:
            for j in range(0,i):
                if m[i,j] != 0:
                    flag = False
                    break
        else:
            break
    if flag:
        print('La matriz es triangular superior')
    else:
        print('La matriz no es triangular superior')
            

#A = np.array( [ [4,9,6], [0,0,-7], [0,0,-1] ])

N = validar('100>N>=2: ', 2, 99)
A = np.empty((N,N))

#Otra forma de inicializar una matriz, en este caso, por filas
for i in range(N):
    #Es posible especificar el tipo del arreglo con dtype
    valores = np.array( input(f'Ingrese valores fila separados por un espacio: ').split(' '), dtype=float )
    A[i,:] = valores #fila i-ésima, todas las columnas (:)

print(A)

#Solución usando métodos (funciones) no numpy
triangular_superior(A)

Ingrese valor 100>N>=2: 3
Ingrese valores fila separados por un espacio: 4 9 6
Ingrese valores fila separados por un espacio: 0 0 -7
Ingrese valores fila separados por un espacio: 0 0 -1
[[ 4.  9.  6.]
 [ 0.  0. -7.]
 [ 0.  0. -1.]]
La matriz es triangular superior


In [4]:
#P4
import numpy as np

def validar(msje, inf, sup):
    numero = int(input('Ingrese valor '+msje))
    if inf!=sup:
        while numero<inf or numero>sup:
            numero = int(input('Error\nIngrese valor '+msje))
    else:
        while numero<inf:
            numero = int(input('Error\nIngrese valor '+msje))
    return numero

def matriz_traspuesta(m):
    x,y = m.shape
    m_t = np.empty((y,x))
    for i in range(x):
        for j in range(y):
            m_t[j,i] = m[i,j]
    return m_t
            
    
#A = np.array([ [4,9], [-7,6], [0,-1] ])

n = validar('n>1: ', 2, 2)
m = validar('m>1: ', 2, 2)
A = np.empty((n,m))

for i in range(n):
    for j in range(m):
        valor = float( input(f'Ingrese valor {i,j}: ') )
        A[i,j] = valor

#Solución usando métodos (funciones) no numpy
print( matriz_traspuesta(A) )
#Alternativa usando numpy: 
#.T entrega la traspuesta del arreglo
print(A.T)

Ingrese valor n>1: 3
Ingrese valor m>1: 2
Ingrese valor (0, 0): 4
Ingrese valor (0, 1): 9
Ingrese valor (1, 0): -7
Ingrese valor (1, 1): 6
Ingrese valor (2, 0): 0
Ingrese valor (2, 1): -1
[[ 4. -7.  0.]
 [ 9.  6. -1.]]
[[ 4. -7.  0.]
 [ 9.  6. -1.]]


In [9]:
#P5
import numpy as np

def validar(msje, inf, sup):
    numero = int(input('Ingrese valor '+msje))
    if inf!=sup:
        while numero<inf or numero>sup:
            numero = int(input('Error\nIngrese valor '+msje))
    else:
        while numero<inf:
            numero = int(input('Error\nIngrese valor '+msje))
    return numero

def multiplica_matrices(m1,m2):
    #Alternativa usando numpy: 
    m1m2 = np.matrix(m1)*np.matrix(m2)
    #Alternativa sin usar numpy:
    #x,y = m1.shape
    #m1m2 = np.zeros((x,y))
    #for i in range(x):
    #    for j in range(x):
    #        s = 0
    #        for k in range(y):
    #            s = s+m1[i,k]*m2[k,j]
    #        m1m2[i,j] = s 
    return m1m2 

def idempotente(m):
    x,y = m.shape
    m2 = multiplica_matrices(m,m)
    s = 0
    for i in range(x):
        for j in range(y):
            if m[i,j]==m2[i,j]:
                s = s+1
    if s==(x*y):
        print('La matriz es idempotente')
    else:
        print('La matriz no es idempotente')
            
#A = np.array( [ [2, -1], [2, -1] ] )
 
n = validar('n>1: ', 2, 2)
A = np.empty((n,n))

for i in range(n):
    valores = np.array( input(f'Ingrese valores fila separados por un espacio: ').split(' '), dtype=float )
    A[i,:] = valores
    
#Solución usando métodos (funciones) no numpy
idempotente(A)
#Alternativa usando numpy: 
#Multiplicación punto a punto usando solamente dot, equivale a multiplicación de matrices
#shape entrega las dimensiones del arreglo (en este caso, 2D)
x,y = A.shape
print( (np.dot(A,A)==A).sum()==(x*y) )
#Alternativa usando numpy: 
#Multiplicación matricial (*). Requiere matrix en lugar de array 
#Al hacer == se compara elemento a elemento y se asigna un True (1) o un False (0)
#Se compara la suma de este arreglo resultante con la cantidad de elementos
A = np.matrix(A)
print( ((A*A)==A).sum()==(x*y) )

Ingrese valor n>1: 2
Ingrese valores fila separados por un espacio: 2 -1
Ingrese valores fila separados por un espacio: 2 -1
La matriz es idempotente
True
True
