In [1]:
import numpy as np

In [2]:
#Cree un arreglo de Numpy en base a una lista
lista = [0, 1, 2]
a = np.array(lista)
print(a)

[0 1 2]


In [3]:
#Cree un arreglo de datos de punto flotante de 32 bits
a = np.array(lista, dtype = "float32")
print(a)

[0. 1. 2.]


In [4]:
#Cree un arreglo de 10 elementos
n = 10
a = np.arange(n)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#Cree un arreglo en el rango [a,b) en pasos de 2
a, b = 5, 20
a = np.arange(a, b, 2)
print(a)

[ 5  7  9 11 13 15 17 19]


In [6]:
#Cree un arreglo de n valores complejos
n = 5
a = np.arange(n, dtype = "complex")
print(a)

[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [7]:
#Obtenga los primeros n elementos de un arreglo
n = 5
a = np.arange(10)
print(a[:n])

[0 1 2 3 4]


In [8]:
#Cambie cada 3 valores de un arreglo por el valor 1
a = np.arange(20, 35)
a[::3] = 1
print(a)

[ 1 21 22  1 24 25  1 27 28  1 30 31  1 33 34]


In [9]:
#Cree un arreglo de dimensiones 3*3 en base a una lista de las mismas dimensiones y
#un arreglo de 2*2*2 en base a una lista de dimensión 1
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(2, 2, 2)
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
#Obtenga un arreglo plano de un arreglo multidimensional
a = A.ravel() # Aplana el arreglo.
b = B.flatten()	# Crea una copia plana.
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8]


In [11]:
#Cree un arreglo de ceros y un arreglo de unos
z = np.zeros(10)
o = np.ones(10)
print(z)
print(o)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
#Cree un arreglo bidimensional (8x8) en patrón de tablero de ajedrez usando 0 y 1
t = np.zeros((8, 8))
t[::2, 1::2] = 1
t[1::2, ::2] = 1
print(t)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [13]:
#Cree una matriz identidad
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
#Multiplique todos los elementos de un arreglo por 100
a = np.arange(10)*100
print(a)

[  0 100 200 300 400 500 600 700 800 900]


In [15]:
#Calcule la multiplicación elemento a elemento de dos arreglos del mismo largo
a = np.arange(100)
b = np.arange(100, 200)
print(a*b)

[    0   101   204   309   416   525   636   749   864   981  1100  1221
  1344  1469  1596  1725  1856  1989  2124  2261  2400  2541  2684  2829
  2976  3125  3276  3429  3584  3741  3900  4061  4224  4389  4556  4725
  4896  5069  5244  5421  5600  5781  5964  6149  6336  6525  6716  6909
  7104  7301  7500  7701  7904  8109  8316  8525  8736  8949  9164  9381
  9600  9821 10044 10269 10496 10725 10956 11189 11424 11661 11900 12141
 12384 12629 12876 13125 13376 13629 13884 14141 14400 14661 14924 15189
 15456 15725 15996 16269 16544 16821 17100 17381 17664 17949 18236 18525
 18816 19109 19404 19701]


In [16]:
# Calcule la multiplicación elemento a elemento y el producto punto de dos matrices de dimensiones iguales
A = np.array([1, 2, 3, 4]).reshape(2, 2)
B = np.array([5, 6, 7, 8]).reshape(2, 2)
print(A*B)
print(np.dot(A, B))
A = np.matrix(A)
B = np.matrix(B)
print(A*B)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [17]:
#Cree un arreglo vacío de 20 elementos.
e = np.empty(20)
print(e)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.60219442e-306
 1.37962456e-306 1.60219035e-306 7.56587585e-307 1.37961302e-306
 1.05699242e-307 8.01097889e-307 1.78020169e-306 7.56601165e-307
 1.02359984e-306 1.33510679e-306 2.22522597e-306 8.01097889e-307
 1.86920057e-306 1.11261027e-306 1.42410974e-306 2.22520559e-306]


In [18]:
#Cree un arreglo con los valores de n divisiones en el rango [a,b]
a, b, n = 0, 10, 21
l = np.linspace(a, b, n)
print(l)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [19]:
#Cree un arreglo con n elementos al azar y uno de n * m
n, m = 5, 4
r = np.random.random(n)
R = np.random.random((n, m))
print(r)
print(R)

[0.61874438 0.12823968 0.48132166 0.59274014 0.02758583]
[[0.78793808 0.48953622 0.40988094 0.96710556]
 [0.65880607 0.42891854 0.74366703 0.33928938]
 [0.84900142 0.57138013 0.33233585 0.06418571]
 [0.20838372 0.21980362 0.00911902 0.21977962]
 [0.279154   0.86709009 0.77229349 0.10131772]]


In [20]:
# Cree un arreglo al azar de n elementos enteros en el rango [0,10)
n = 100
r = np.random.randint(0, 10, n)
print(r)

[3 1 1 1 7 9 5 2 6 6 5 9 7 6 7 4 7 6 8 5 2 2 1 0 5 8 4 0 1 6 3 9 2 4 8 2 7
 0 6 6 2 2 8 0 5 7 5 2 9 8 0 9 4 0 4 0 7 0 0 4 3 6 0 2 4 6 7 1 9 9 1 4 8 1
 9 6 1 4 8 1 9 3 9 4 5 9 9 9 3 2 4 8 2 2 4 4 2 9 8 1]


In [21]:
#Obtenga la suma de todos los valores de un arreglo
s = np.sum(np.arange(100))
print(s)

4950


In [22]:
#Obtenga el valor máximo de un arreglo
r = np.random.random(100)
print(r.max())

0.9982080723837975


In [23]:
#Concatene dos arreglos unidimensionales
a = np.arange(10)*100
b = np.arange(5)
print(np.concatenate((a, b)))

[  0 100 200 300 400 500 600 700 800 900   0   1   2   3   4]


In [24]:
#Concatene dos arreglos verticalmente y dos horizontalmente
A = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])
B = np.array([[1, 2],
              [3, 4]])
print(np.vstack((A, B)))
B = B.reshape(4, 1)
print(np.hstack((A, B)))#o column_stack((A,B))

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [1 2]
 [3 4]]
[[1 2 1]
 [3 4 2]
 [5 6 3]
 [7 8 4]]


In [25]:
#Dado un arreglo arbitrario aplique una máscara de bits a cada elemento de este
r = np.bitwise_and(np.arange(10),0b0010) #np.arange(10) & 0b0010
print(r)

[0 0 2 2 0 0 2 2 0 0]


In [26]:
#Encuentre los elementos distintos entre dos arreglos de estados binarios
A = np.array([[0, 1, 1],
              [1, 0, 0],
              [0, 1, 0]])
B = np.array([[1, 1, 0],
              [0, 0, 0],
              [0, 1, 1]])
print(np.bitwise_xor(A,B))#A^B

[[1 0 1]
 [1 0 0]
 [0 0 1]]


In [27]:
#Dado tres arreglos x, y, z, obtenga una arreglo nuevo con los elementos de estos intercalados
x = np.random.random(10)
y = np.random.random(10)
z = np.random.random(10)
n = np.empty(3*len(x))
n[::3] = x
n[1::3] = y
n[2::3] = z
print(n)

[0.77281259 0.22197294 0.77156135 0.86394795 0.90794586 0.33942077
 0.715528   0.90194253 0.67088897 0.50640233 0.68054912 0.49819823
 0.9524982  0.76810142 0.21560446 0.32563529 0.72757684 0.25549668
 0.80728759 0.48577734 0.56361037 0.93442985 0.73615782 0.89524358
 0.28028494 0.18790494 0.26718386 0.86728749 0.71364028 0.61652474]
